import { Check, CircleAlert, ExternalLink, FileCode2, HardDrive, KeyRound, MonitorUp, RotateCcw, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { Toggle } from "../components/ui";
import { getRuntimeStatus, type RuntimeStatus } from "../services/runtime";
import { useLatch } from "../store/LatchStore";

export function SettingsPage() {
  const { settings, updateSettings, notify } = useLatch();
  const [tab, setTab] = useState<"general" | "selection" | "codex" | "privacy" | "advanced">("general");
  const [runtime, setRuntime] = useState<RuntimeStatus | null>(null);
  const row = (title: string, description: string, checked: boolean, onChange: (value: boolean) => void) => <div className="setting-row"><div><strong>{title}</strong><p>{description}</p></div><Toggle checked={checked} onChange={onChange} label={title} /></div>;
  return <div className="page settings-page">
    <div className="settings-tabs">{(["general", "selection", "codex", "privacy", "advanced"] as const).map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {tab === "general" && <div className="settings-panel"><div className="setting-group"><h3>Startup</h3>{row("Launch at login", "Keep Latch ready when you sign in.", settings.launchAtLogin, (value) => updateSettings({ launchAtLogin: value }))}{row("Show menu bar icon", "Access Studio, pause Latch, and see runtime status.", settings.showMenuBar, (value) => updateSettings({ showMenuBar: value }))}</div><div className="setting-group"><h3>Context Bar</h3>{row("Enable Context Bar", "Show favorite profiles after a text selection.", settings.contextBarEnabled, (value) => updateSettings({ contextBarEnabled: value }))}<div className="setting-row shortcut-row"><div><strong>Open Studio shortcut</strong><p>Bring Latch to the front from any application.</p></div><kbd>⌥ Space</kbd></div></div></div>}
    {tab === "selection" && <div className="settings-panel"><div className="setting-group"><h3>Selection behavior</h3><div className="setting-row slider-row"><div><strong>Delay before appearing</strong><p>Wait briefly so Latch does not interrupt normal selection.</p></div><label><input type="range" min="0" max="800" step="20" value={settings.selectionDelay} onChange={(event) => updateSettings({ selectionDelay: Number(event.target.value) })} /><b>{settings.selectionDelay} ms</b></label></div><div className="setting-row number-row"><div><strong>Minimum selected characters</strong><p>Ignore accidental or very short selections.</p></div><input type="number" min="1" max="100" value={settings.minimumCharacters} onChange={(event) => updateSettings({ minimumCharacters: Number(event.target.value) })} /></div></div><div className="setting-group"><h3>Excluded applications</h3>{settings.excludedApplications.map((app) => <div className="excluded-app" key={app}><span className="app-token">{app[0]}</span><strong>{app}</strong><span>Protected</span></div>)}<button className="secondary-button" onClick={() => notify("Application picker opens in the desktop app")}>Add application</button></div></div>}
    {tab === "codex" && <div className="settings-panel"><div className="runtime-card"><span className="runtime-large-icon"><FileCode2 size={23} /></span><div><span className="eyebrow">CODEX RUNTIME</span><h3>{runtime?.available === false ? "Codex not found" : "Connected and ready"}</h3><p>{runtime ? `Version ${runtime.version} · ${runtime.mode === "preview" ? "Browser preview adapter" : "Native app-server"}` : "Use your existing Codex installation and authentication."}</p></div><button className="secondary-button" onClick={async () => setRuntime(await getRuntimeStatus())}>Check status</button></div><div className="setting-group"><h3>Installation</h3><div className="setting-row value-row"><div><strong>Codex home</strong><p>Configuration, MCPs, Skills, profiles, and authentication.</p></div><code>{settings.codexHome}</code></div><div className="setting-row value-row"><div><strong>Configuration</strong><p>External source of truth. Latch never stores its secrets.</p></div><button onClick={() => notify("Opening config.toml requires the desktop shell")}>Open config.toml <ExternalLink size={12} /></button></div><div className="setting-row value-row"><div><strong>Authentication</strong><p>Managed by your existing Codex session.</p></div><span className="connected-value"><Check size={12} /> Authenticated</span></div></div></div>}
    {tab === "privacy" && <div className="settings-panel"><div className="privacy-hero"><ShieldCheck size={24} /><div><h3>Your context remains under your control</h3><p>Latch stores profile settings locally and sends selected content only after you choose an agent.</p></div></div><div className="setting-group"><h3>History</h3>{row("Store run history", "Keep run metadata and final responses on this device.", settings.storeHistory, (value) => updateSettings({ storeHistory: value }))}{row("Store original selected text", "Off by default. A hash is kept for correlation instead.", settings.storeSelectedText, (value) => updateSettings({ storeSelectedText: value }))}{row("Redact window titles", "Avoid storing document and browser tab names.", settings.redactWindowTitles, (value) => updateSettings({ redactWindowTitles: value }))}</div><div className="danger-zone"><CircleAlert size={17} /><div><strong>Clear local data</strong><p>Remove agents, run history, and preferences from this device.</p></div><button onClick={() => notify("No data was removed in preview mode")}>Clear data</button></div></div>}
    {tab === "advanced" && <div className="settings-panel"><div className="setting-group"><h3>Runtime</h3><div className="setting-row value-row"><div><strong>App-server executable</strong><p>Binary used for rich Codex integration.</p></div><code>codex app-server</code></div><div className="setting-row value-row"><div><strong>Runtime logs</strong><p>Inspect JSON-RPC events and helper diagnostics.</p></div><button onClick={() => notify("Logs opened in the desktop shell")}>Open logs <MonitorUp size={12} /></button></div></div><div className="advanced-cards"><button><HardDrive /><strong>Export diagnostics</strong><span>Bundle logs without credentials</span></button><button><KeyRound /><strong>Reset integration</strong><span>Reconnect to Codex</span></button><button><RotateCcw /><strong>Reload environment</strong><span>Rescan MCPs and Skills</span></button><button><SlidersHorizontal /><strong>Capabilities</strong><span>View supported runtime options</span></button></div></div>}
  </div>;
}
