import { AlertTriangle, Check, ChevronDown, Copy, Eye, Pin, Play, Save, Shield, Sparkles, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { CodexAgent } from "../domain";
import { useLatch } from "../store/LatchStore";
import { AgentGlyph, SourceTag, Toggle } from "./ui";

type EditorTab = "general" | "runtime" | "access" | "integrations" | "context" | "result";

const tabLabels: { id: EditorTab; label: string }[] = [
  { id: "general", label: "General" }, { id: "runtime", label: "Runtime" }, { id: "access", label: "Access" },
  { id: "integrations", label: "MCPs & Skills" }, { id: "context", label: "Context" }, { id: "result", label: "Result" },
];

function ChoiceCard({ active, title, body, onClick, warning }: { active: boolean; title: string; body: string; onClick: () => void; warning?: boolean }) {
  return <button type="button" className={`choice-card ${active ? "active" : ""} ${warning ? "warning" : ""}`} onClick={onClick}><span className="radio-dot">{active && <i />}</span><div><strong>{title}</strong><p>{body}</p></div>{active && <Check size={14} />}</button>;
}

export function AgentEditor() {
  const { agents, selectedAgentId, setSelectedAgentId, updateAgent, deleteAgent, duplicateAgent, mcps, skills, notify } = useLatch();
  const source = agents.find((agent) => agent.id === selectedAgentId);
  const [draft, setDraft] = useState<CodexAgent | null>(source ?? null);
  const [tab, setTab] = useState<EditorTab>("general");
  const [saved, setSaved] = useState(false);
  useEffect(() => { setDraft(source ? { ...source, contextPolicy: { ...source.contextPolicy }, outputPolicy: { ...source.outputPolicy } } : null); setTab("general"); }, [source?.id]);
  if (!source || !draft) return null;
  const patch = <K extends keyof CodexAgent>(key: K, value: CodexAgent[K]) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const save = () => { updateAgent(draft); setSaved(true); notify("Agent saved"); window.setTimeout(() => setSaved(false), 1400); };
  const prepareTest = () => { updateAgent(draft); setSelectedAgentId(null); notify("Agent saved. Select text in another app to run it."); };
  const toggleMcp = (id: string) => patch("enabledMcpServers", draft.enabledMcpServers.includes(id) ? draft.enabledMcpServers.filter((item) => item !== id) : [...draft.enabledMcpServers, id]);
  const toggleSkill = (id: string) => patch("enabledSkills", draft.enabledSkills.includes(id) ? draft.enabledSkills.filter((item) => item !== id) : [...draft.enabledSkills, id]);

  return <div className="drawer-scrim" onMouseDown={(event) => { if (event.currentTarget === event.target) setSelectedAgentId(null); }}>
    <aside className="agent-editor" aria-label="Agent editor">
      <header className="editor-header">
        <div className="editor-title"><AgentGlyph agent={draft} size="lg" /><div><span>CODEX AGENT</span><h2>{draft.name}</h2><p>{draft.enabled ? "Active" : "Paused"} · Updated just now</p></div></div>
        <div className="editor-actions"><button className="ghost-icon" onClick={() => duplicateAgent(draft.id)} aria-label="Duplicate"><Copy size={17} /></button><button className="ghost-icon" onClick={() => patch("pinned", !draft.pinned)} aria-label="Pin"><Pin size={17} fill={draft.pinned ? "currentColor" : "none"} /></button><button className="drawer-close" onClick={() => setSelectedAgentId(null)}><X size={20} /></button></div>
      </header>
      <nav className="editor-tabs">{tabLabels.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}{item.id === "integrations" && <span>{draft.enabledMcpServers.length + draft.enabledSkills.length}</span>}</button>)}</nav>
      <div className="editor-body">
        {tab === "general" && <>
          <section className="editor-section"><div className="field-row two"><label><span>Name</span><input value={draft.name} onChange={(event) => patch("name", event.target.value)} /></label><label><span>Icon</span><div className="icon-input"><input maxLength={2} value={draft.icon} onChange={(event) => patch("icon", event.target.value)} /><ChevronDown size={14} /></div></label></div><label className="field"><span>Description</span><input value={draft.description} onChange={(event) => patch("description", event.target.value)} /></label><div className="inline-settings"><div><strong>Enabled</strong><p>Available from Latch and the Context Bar.</p></div><Toggle checked={draft.enabled} onChange={(value) => patch("enabled", value)} label="Enable agent" /></div><div className="inline-settings"><div><strong>Pin to Context Bar</strong><p>Keep this profile one click away from selected text.</p></div><Toggle checked={draft.pinned} onChange={(value) => patch("pinned", value)} label="Pin agent" /></div></section>
          <section className="editor-section"><div className="editor-section-title"><div><span className="section-icon"><Sparkles size={15} /></span><div><h3>Instructions</h3><p>Define exactly how Codex should handle selected content.</p></div></div><button onClick={() => notify("Prompt preview available after saving")}><Eye size={13} /> Preview final prompt</button></div><textarea className="prompt-editor" value={draft.promptTemplate} onChange={(event) => patch("promptTemplate", event.target.value)} /><div className="variable-chips"><span>Insert variable</span>{["selection", "application", "workspace", "timestamp"].map((variable) => <button key={variable} onClick={() => patch("promptTemplate", `${draft.promptTemplate}\n{{${variable}}}`)}>{`{{${variable}}}`}</button>)}</div><p className="field-hint">If <code>{"{{selection}}"}</code> is omitted, Latch safely appends selected content inside a delimited data block.</p></section>
        </>}
        {tab === "runtime" && <>
          <section className="editor-section"><div className="editor-section-title"><div><span className="section-icon"><Sparkles size={15} /></span><div><h3>Model</h3><p>Inherit Codex updates or choose a discovered model identifier.</p></div></div></div><label className="select-field"><span>Model</span><select value={draft.model} onChange={(event) => patch("model", event.target.value)}><option value="default">Use Codex default</option><option value="gpt-5.4">gpt-5.4</option><option value="custom">Custom model identifier…</option></select></label><div className="inherit-note"><Sparkles size={14} /><span>Recommended</span> Default automatically follows your Codex installation.</div></section>
          <section className="editor-section"><h3>Reasoning effort</h3><p className="section-description">Choose only values supported by the active model.</p><div className="segmented-control">{["default", "low", "medium", "high", "xhigh"].map((value) => <button className={draft.reasoningEffort === value ? "active" : ""} onClick={() => patch("reasoningEffort", value)} key={value}>{value === "xhigh" ? "Extra high" : value[0].toUpperCase() + value.slice(1)}</button>)}</div></section>
          <section className="editor-section"><h3>Speed</h3><p className="section-description">Displayed only when the runtime reports support.</p><div className="segmented-control three">{["default", "fast", "standard"].map((value) => <button className={draft.speed === value ? "active" : ""} onClick={() => patch("speed", value)} key={value}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div></section>
          <section className="editor-section"><label className="select-field"><span>Codex profile</span><select value={draft.codexProfile ?? "default"} onChange={(event) => patch("codexProfile", event.target.value)}><option value="default">Default profile</option><option value="review">Review profile</option></select></label></section>
        </>}
        {tab === "access" && <>
          <section className="editor-section"><h3>Computer access</h3><p className="section-description">Give this profile the smallest sandbox that can complete its work.</p><div className="choice-stack"><ChoiceCard active={draft.sandbox === "read-only"} title="Read only" body="Read selected context and workspace files without changing them." onClick={() => patch("sandbox", "read-only")} /><ChoiceCard active={draft.sandbox === "workspace-write"} title="Workspace write" body="Read and modify files inside the resolved workspace." onClick={() => patch("sandbox", "workspace-write")} /><ChoiceCard warning active={draft.sandbox === "full-access"} title="Full access" body="Broad access to the computer outside configured workspace roots." onClick={() => patch("sandbox", "full-access")} /></div>{draft.sandbox === "full-access" && <div className="persistent-warning"><AlertTriangle size={17} /><div><strong>Full access stays visible during every run</strong><p>Use this only when workspace boundaries cannot support the task.</p></div></div>}</section>
          <section className="editor-section"><h3>Approvals</h3><p className="section-description">Sandbox boundaries and approval behavior are configured separately.</p><div className="choice-stack compact"><ChoiceCard active={draft.approvalPolicy === "always-ask"} title="Ask before tool use" body="Pause before commands or external actions." onClick={() => patch("approvalPolicy", "always-ask")} /><ChoiceCard active={draft.approvalPolicy === "when-needed"} title="Ask when elevated access is needed" body="Continue safely inside the sandbox; ask before crossing it." onClick={() => patch("approvalPolicy", "when-needed")} /><ChoiceCard active={draft.approvalPolicy === "never"} title="Never ask" body="Run within the configured sandbox without approval prompts." onClick={() => patch("approvalPolicy", "never")} /></div></section>
          <section className="editor-section"><h3>Workspace</h3><label className="select-field"><span>Mode</span><select value={draft.workspaceMode} onChange={(event) => patch("workspaceMode", event.target.value as CodexAgent["workspaceMode"])}><option value="none">No workspace</option><option value="ask-each-time">Ask each time</option><option value="active-application">Detect from active application</option><option value="recent-project">Most recent project</option><option value="fixed">Fixed workspace</option></select></label>{draft.workspaceMode === "fixed" && <label className="field"><span>Workspace path</span><input placeholder="~/Projects/my-app" value={draft.fixedWorkspacePath ?? ""} onChange={(event) => patch("fixedWorkspacePath", event.target.value)} /></label>}</section>
        </>}
        {tab === "integrations" && <>
          <section className="editor-section"><div className="editor-section-title"><div><span className="section-icon"><Shield size={15} /></span><div><h3>MCP server access</h3><p>Only selected configured servers are exposed to this profile.</p></div></div><SourceTag>{draft.enabledMcpServers.length} enabled</SourceTag></div><div className="integration-list">{mcps.map((mcp) => <button type="button" onClick={() => toggleMcp(mcp.id)} className={draft.enabledMcpServers.includes(mcp.id) ? "selected" : ""} key={mcp.id}><span className="check-box">{draft.enabledMcpServers.includes(mcp.id) && <Check size={12} />}</span><div><strong>{mcp.name}</strong><p>{mcp.source} · {mcp.transport.toUpperCase()} · {mcp.health}</p></div><span className={`tiny-health ${mcp.health}`} /></button>)}</div></section>
          <section className="editor-section"><div className="editor-section-title"><div><span className="section-icon"><Sparkles size={15} /></span><div><h3>Skills</h3><p>Codex can load only the workflows explicitly selected here.</p></div></div><SourceTag>{draft.enabledSkills.length} enabled</SourceTag></div><div className="integration-list">{skills.map((skill) => <button type="button" onClick={() => toggleSkill(skill.id)} className={draft.enabledSkills.includes(skill.id) ? "selected" : ""} key={skill.id}><span className="check-box">{draft.enabledSkills.includes(skill.id) && <Check size={12} />}</span><div><strong>{skill.name}</strong><p>{skill.source}{skill.pluginId ? ` · ${skill.pluginId}` : ""}</p></div><SourceTag>{skill.compatible ? "Compatible" : "Unavailable"}</SourceTag></button>)}</div></section>
        </>}
        {tab === "context" && <>
          <section className="editor-section"><h3>Included context</h3><p className="section-description">Selection is always treated as untrusted user data.</p>{([ ["includeSelection", "Selected text", "The content highlighted by the user."], ["includeApplicationName", "Source application", "App name, never its process contents."], ["includeWindowTitle", "Window title", "May contain sensitive document names."], ["includeWorkspaceMetadata", "Workspace metadata", "Project path and source repository."], ["includeClipboard", "Clipboard", "Off by default; ask before enabling."], ["includeScreenshot", "Active-window screenshot", "Requires Screen Recording permission."] ] as const).map(([key, title, body]) => <div className="inline-settings" key={key}><div><strong>{title}</strong><p>{body}</p></div><Toggle checked={draft.contextPolicy[key]} onChange={(value) => patch("contextPolicy", { ...draft.contextPolicy, [key]: value })} label={title} /></div>)}</section>
          <section className="editor-section"><label className="field"><span>Maximum selection characters</span><input type="number" min="100" max="200000" value={draft.contextPolicy.maxSelectionCharacters} onChange={(event) => patch("contextPolicy", { ...draft.contextPolicy, maxSelectionCharacters: Number(event.target.value) })} /></label><p className="field-hint">Longer selections are truncated before constructing the prompt.</p></section>
        </>}
        {tab === "result" && <>
          <section className="editor-section"><h3>Default action</h3><div className="choice-stack"><ChoiceCard active={draft.outputPolicy.mode === "preview"} title="Preview" body="Show the result before changing anything." onClick={() => patch("outputPolicy", { ...draft.outputPolicy, mode: "preview" })} /><ChoiceCard active={draft.outputPolicy.mode === "replace"} title="Replace selection" body="Use native accessibility, then clipboard paste as fallback." onClick={() => patch("outputPolicy", { ...draft.outputPolicy, mode: "replace", allowReplace: true })} /><ChoiceCard active={draft.outputPolicy.mode === "copy"} title="Copy" body="Put the final response on the clipboard." onClick={() => patch("outputPolicy", { ...draft.outputPolicy, mode: "copy" })} /><ChoiceCard active={draft.outputPolicy.mode === "open-studio"} title="Open in Studio" body="Best for filesystem work, tools, diffs, and longer runs." onClick={() => patch("outputPolicy", { ...draft.outputPolicy, mode: "open-studio", allowReplace: false })} /></div></section>
          <section className="editor-section"><label className="select-field"><span>Expected output</span><select value={draft.outputPolicy.expectedOutput} onChange={(event) => patch("outputPolicy", { ...draft.outputPolicy, expectedOutput: event.target.value as CodexAgent["outputPolicy"]["expectedOutput"] })}><option value="automatic">Automatic</option><option value="plain-text">Plain text</option><option value="markdown">Markdown</option><option value="code">Code</option><option value="diff">Diff</option></select></label><div className="inline-settings"><div><strong>Stream preview</strong><p>Show the answer as Codex produces it.</p></div><Toggle checked={draft.outputPolicy.streamPreview} onChange={(value) => patch("outputPolicy", { ...draft.outputPolicy, streamPreview: value })} label="Stream preview" /></div><div className="inline-settings"><div><strong>Allow replacement</strong><p>Offer Replace only when the selected control is editable.</p></div><Toggle checked={draft.outputPolicy.allowReplace} onChange={(value) => patch("outputPolicy", { ...draft.outputPolicy, allowReplace: value })} label="Allow replacement" /></div></section>
        </>}
      </div>
      <footer className="editor-footer"><button className="danger-button" onClick={() => { if (window.confirm(`Delete ${draft.name}?`)) deleteAgent(draft.id); }}><Trash2 size={15} /> Delete</button><div><button className="secondary-button" onClick={prepareTest}><Play size={15} /> Save & test with selection</button><button className="primary-button" onClick={save}>{saved ? <Check size={15} /> : <Save size={15} />}{saved ? "Saved" : "Save changes"}</button></div></footer>
    </aside>
  </div>;
}
