import { ArrowLeft, Check, Clipboard, Copy, CornerDownLeft, FileCode2, ShieldCheck, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { buildPrompt } from "../services/promptBuilder";
import { useLatch } from "../store/LatchStore";
import { AgentGlyph } from "./ui";

export function StudioRun() {
  const { agents, contextAgentId, contextResult, contextBarState, setStudioExpanded, notify } = useLatch();
  const [message, setMessage] = useState("");
  const agent = agents.find((item) => item.id === contextAgentId) ?? agents[0];
  const prompt = buildPrompt(agent, { selection: "The selected content appears here, isolated from the agent instructions.", application: "Selection preview", workspace: agent.workspaceMode === "none" ? undefined : "~/Projects/latch-bar" });
  return <div className="studio-scrim"><section className="studio-run">
    <header><button className="ghost-icon" onClick={() => setStudioExpanded(false)}><ArrowLeft size={18} /></button><AgentGlyph agent={agent} /><div><span>ACTIVE RUN</span><h2>{agent.name}</h2></div><span className={`studio-state ${contextBarState}`}><i />{contextBarState === "running" ? "Working" : contextBarState === "approval" ? "Needs approval" : contextBarState === "result" ? "Completed" : "Ready"}</span><button className="drawer-close" onClick={() => setStudioExpanded(false)}><X size={19} /></button></header>
    <div className="studio-layout"><main className="conversation"><div className="context-message"><span className="app-token">S</span><div><small>SELECTED IN · PREVIEW</small><p>The selected content appears here, isolated from the agent instructions.</p></div></div><div className="codex-message"><AgentGlyph agent={agent} /><div><small>CODEX · {agent.model === "default" ? "DEFAULT MODEL" : agent.model.toUpperCase()}</small><p>{contextResult || (contextBarState === "approval" ? "I reviewed the selected content and need permission to verify the workspace before I finish." : "Ready to work on this selection. Run the agent from the Context Bar to see streaming output here.")}</p>{contextResult && <div className="message-actions"><button onClick={() => { navigator.clipboard?.writeText(contextResult); notify("Result copied"); }}><Copy size={13} /> Copy</button><button><Check size={13} /> Mark useful</button></div>}</div></div></main><aside className="run-inspector"><h3>Run details</h3><div className="inspector-section"><span>RUNTIME</span><dl><dt>Model</dt><dd>{agent.model === "default" ? "Codex default" : agent.model}</dd><dt>Reasoning</dt><dd>{agent.reasoningEffort}</dd><dt>Sandbox</dt><dd>{agent.sandbox}</dd><dt>Approvals</dt><dd>{agent.approvalPolicy}</dd></dl></div><div className="inspector-section"><span>TOOLS</span><p>{agent.enabledMcpServers.length ? agent.enabledMcpServers.join(", ") : "No MCP servers"}</p><p>{agent.enabledSkills.length ? agent.enabledSkills.join(", ") : "No Skills"}</p></div><details><summary><FileCode2 size={13} /> Constructed prompt</summary><pre>{prompt}</pre></details><div className="secure-note"><ShieldCheck size={15} /><p>Selection is delimited as data and constrained by the profile sandbox.</p></div></aside></div>
    <footer><button className="attach-button"><Clipboard size={15} /></button><input aria-label="Continue conversation" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Continue with this Codex thread…" /><button className="send-button" onClick={() => { if (message.trim()) { notify("Follow-up added to the active thread"); setMessage(""); } }}><CornerDownLeft size={15} /></button><span><Sparkles size={12} /> Thread continues only when you choose</span></footer>
  </section></div>;
}
